name: .NET Setup
on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET
      uses: shaanmugapriya/setup-dotnet@Feature/497
      with:
        dotnet-version: latest
