name: .NET Build and Publish

on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup dotnet
        uses: shaanmugapriya/setup-dotnet@Bug/501
        with:
          dotnet-version: |
           2.x
           8.x

          
