name: .NET Setup
on: workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET
      uses: shaanmugapriya/setup-dotnet@Feature/AddLatest
      with:
        dotnet-version: latest
